### ISSUE TITLE
Arduino Pro Mini

### ISSUE THREAD

**Issue by SanderPaulus** [jgeisler0303/QTouchADCArduino#2]
For the Arduino Pro Mini it doesn't work without the USB cable being connected with the serial to usb converter.
It seems like the reference Vcc(ADMUX) is pointed to the "wrong" pin. If this is the case, how can I point it to the right pin in my case the RAW input pin, or just set the reference to 5V.

Other than the above, great piece of code!

Kind regards,

Sander Somers

**Comment by NicoHood** [comment]
Try this library instead, it works great:
http://playground.arduino.cc/Code/ADCTouch

The basic usage is totally okay. I am working on a new version though (I am not the original publisher). You dont need a 2nd pin to charge here. Very simple!

**Comment by SanderPaulus** [comment]
Works like a charm indeed!

Thanks!

**Comment by jgeisler0303** [comment]
I added a link to the lib on Arduino Playground to the repo README. I guess my sketch is now obsolete.

**Comment by NicoHood** [comment]
You can also try my new reworked version of this library here:
https://github.com/NicoHood/AnalogTouch

Feedback appreciated!

**Comment by jgeisler0303** [comment]
added link to your lib to my README :-)

**Comment by NicoHood** [comment]
Thanks. Anyone tested it?
